[package]
name = "dns-transport"
version = "0.1.0"
authors = ["Benjamin Sago <ogham@bsago.me>"]
edition = "2018"


[dependencies]
derive_more = "0.99"

# dns wire protocol
dns = { path = "../dns" }

# logging
log = "0.4"

# tls networking
native-tls = { version = "0.2", optional = true }

# http response parsing
httparse = { version = "1.3", optional = true }

[features]
default = []  # these are enabled in the main dog crate
tls   = ["native-tls"]
https = ["native-tls", "httparse"]
